In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("FashionDataset.csv")

In [3]:
df.head()

,Unnamed: 0,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women

In [5]:
df.shape

(30758, 8)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30758 entries, 0 to 30757
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  30758 non-null  int64
 1   BrandName   30758 non-null  object
 2   Deatils     30758 non-null  object
 3   Sizes       30758 non-null  object
 4   MRP         30758 non-null  object
 5   SellPrice   30758 non-null  object
 6   Discount    30758 non-null  object
 7   Category    30758 non-null  object
dtypes: int64(1), object(7)
memory usage: 1.9+ MB

In [7]:
df.columns

Index(['Unnamed: 0', 'BrandName', 'Deatils', 'Sizes', 'MRP', 'SellPrice',
       'Discount', 'Category'],
      dtype='object')

In [8]:
df.isnull().sum()

Unnamed: 0    0
BrandName     0
Deatils       0
Sizes         0
MRP           0
SellPrice     0
Discount      0
Category      0
dtype: int64

In [9]:
df.duplicated().sum()

1331

In [13]:
df.drop_duplicates(inplace= True)

In [14]:
df.duplicated().sum()

0

In [15]:
df.nunique()

Unnamed: 0       26
BrandName       275
Deatils       23877
Sizes          1172
MRP            1097
SellPrice      2046
Discount         66
Category          7
dtype: int64

In [18]:
df.drop(columns=['Unnamed: 0'] , inplace = True)

In [20]:
df.dtypes

BrandName    object
Deatils      object
Sizes        object
MRP          object
SellPrice    object
Discount     object
Category     object
dtype: object

In [21]:
df.head()

,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women

In [23]:
df.rename(columns= {'Deatils' : "Details"} , inplace= True )

In [24]:
df.isna().sum()

BrandName    0
Details      0
Sizes        0
MRP          0
SellPrice    0
Discount     0
Category     0
dtype: int64

In [26]:
df['BrandName'] = df['BrandName'].apply(lambda x : x.capitalize())

In [27]:
df['Sizes'] = df['Sizes'].replace("NaN" , "Na Valued")

In [28]:
df['Discount'] = df['Discount'].replace("NaN" , "Na Discount")

In [29]:
df.reset_index().drop(columns= 'index' , inplace = True)

In [30]:
df.to_csv("CleanedFashionDataset.csv")
df.to_csv("CleanedFashionDatasetWithoitIndex")